### ISSUE TITLE
Error in ARAM game

### ISSUE THREAD

**Issue by FaintWhisper** [f1uzz/shadow#1]
Hi, thanks for the program, but I got an error when picking champ in an ARAM game, here is the screenshot:

![image](https://user-images.githubusercontent.com/25695666/76539246-cdd37400-6480-11ea-8a80-17701af1b3bc.png)

It happens all the time with ARAM, I haven't tried it on other modes.

**Comment by f1uzz** [comment]
Have you tried it again recently? Sorry, I haven't checked this repo in a while

**Comment by FaintWhisper** [comment]
No, not really, sorry, I will try in a few days and report it here.

**Comment by f1uzz** [comment]
Thanks. I’ve tested the latest version (1.6.0) in all modes and it is working for me.

**Comment by FaintWhisper** [comment]
Sorry for the waiting, I just tried, no luck :(

Using Python 3.7 and all dependencies installed, this time it throws a syntax error.

**Comment by f1uzz** [comment]
Sorry, I forgot to update the README; it actually requires Python 3.8 because I used the walrus operator (:=) a couple times. I can also remove those so (I think) it will work with 3.7 as well.

Thanks!

**Comment by f1uzz** [comment]
Should be fixed now after 003838c0ccf3778e717b36b449d7677a7f865b64 , try pulling and running with 3.7

**Comment by FaintWhisper** [comment]
That's what was causing the problem.

Thanks for your work, keep it up!

**Comment by f1uzz** [comment]
No problem, thank you so much for using this project!
